### ISSUE TITLE
e-mail addressforall, problemas, sugestões e solicitações

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/suporte#1]
A caixa postal da AddressForAll está sendo monitorada pelo @crebollobr.  Ele é o nosso "ouvidor técnico" para problemas com o site e o e-mail.

Postar **nesta *issue* qualquer  sugestão, solicitação, dúvida ou alerta de falha**.

**Comment by ppKrauss** [comment]
Implementar o `operacao@addressForAll.org`  como alias para os responsáveis, conforme definido por @ThierryAJean.

**Comment by crebollobr** [comment]
Não foi fechado na época.
Se precisar de mais alguma coisa reabrir

**Comment by crebollobr** [comment]
Não foi fechado na época.
Se precisar de mais alguma coisa reabrir
