### ISSUE TITLE
Um certificado HTTPS para cada domínio  

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/suporte#11]
Aparentemente falta para OSM.codes. Resta conferir se subdomínios terão problemas e quais os demais domínios, como digital-guard.org

**Comment by ppKrauss** [comment]
Precisamos aguardar fechamento da #17

**Comment by crebollobr** [comment]
Fiz certificado em todos os dominios válidos

**Comment by cchness** [comment]
Verificar o erro de certificado em #18.
