### ISSUE TITLE
Atividades de suporte periódicas

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/suporte#12]
A administração precisa registrar e acordar com suporte as atividades periódicas:

* sustentação do banco de dados e APIs: sempre que falhar ou sair do ar, colocar de volta.
* monitoramento/sustentação de segurança (receber e-mails de diagnóstico e analisar alertas)
* atualizações do Linux

## Atualizações linux
Não é necessário mais que 1 vez por mês, exceto se "security update" quando avaliados como urgentes. Em geral a atividade não dá trabalho, se resume a executar `sudo apt update; sudo apt upgrade` e acompanhar eventuais falhas. Pode tomar mais tempo (~10 minutos) quando for requerido *restart*. Abaixo um exemplo das mensagens de login que alertam incidentes.

```
67 updates can be applied immediately.
1 of these updates is a standard security update.
To see these additional updates run: apt list --upgradable

1 updates could not be installed automatically. For more details,
see /var/log/unattended-upgrades/unattended-upgrades.log

*** System restart required ***
```

**Comment by crebollobr** [comment]
Apontamento de horário na planilha
