### ISSUE TITLE
API para onedrive - teste de conceito

### ISSUE THREAD

**Issue by ThierryAJean** [AddressForAll/suporte#13]
Carlos fez um teste do Onedrive para p Digital Preservation. Funcionou com a conta pessoal dele.

**Comment by ppKrauss** [comment]
ver https://docs.google.com/spreadsheets/d/1CL6f0I9DSpqKxKC7QNJGCfyabq7mDOVab5QBGV5VLOk/edit#gid=0

**Comment by crebollobr** [comment]
O Dono das pastas tem que ser o mesmo usuário que compartilha os links. 
Recomendo usar o usuário operação para para hospedar os dados e para compartilhar os links. 
Para isso todos as pastas e arquivos devem ser transmitidos para a conta operação.

Se @ThierryAJean  e @ppKrauss estiverem de acordo, transfiro os arquivos.

**Comment by crebollobr** [comment]
Cinco links na planilha @ppKrauss

**Comment by ThierryAJean** [comment]
@ppKrauss Parece nos que mudar os nossos arquivos do Onedraive do Thierry para o Onedrive do operacao@addressforall.org  não é tão interessante, já que varios patrocinadores e prospects têm acesso aos links Onedrive atuais. Como, a medio/longo prazo, tudo estará no servidor preservação digital, melhor esperar este momento. Concorda?

**Comment by ppKrauss** [comment]
> @ppKrauss Parece nos que mudar os nossos arquivos do Onedraivedo ... não é tão interessante, ... Concorda?

Acho que ainda temos poucos arquivos e  espaço de sobra, não tem problema manter nos dois, mas de hoje em diante só coloca no Operacao.   Como não iniciamos parceria nem pagamento de "disco frio" para os backups em nuvem &mdash; o mais barato do mundo seria Alibabacloud, mas qualquer parceiro dando 50% de desconto ou mais será mais barato ainda  &mdash;, precisamos testar esse tipo de solução. O Claiton com ajuda do Carlos implementará semana que vem ou a outra. A solução valerá para qualquer outra "nuvem de backup", é indiferente.

O que precisamos passar para nossos cliente é o link persistente, [**PURL**](https://en.wikipedia.org/wiki/Persistent_uniform_resource_locator), que já temos, é com **prefixo `dl.digital-guard.org`**.

Exemplo: http://dl.digital-guard.org/ed072b0391d6c4a9bd76237b4ebb55de4f00ff0b73325d715d35baf29f41278e.zip
