### ISSUE TITLE
Redistribuir configurações NGINX e criar template mustache dos fragmentos

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/suporte#17]
Ao invés de manter tudo num só arquivo de `/etc/nginx/sites-available/`, refatorar e separar em arquivos, por domínios. No final revisar se tudo ok com HTTPS.  Como tem um pouco de lixo, podemos ir **fazendo e testando** aos poucos e nesta ordem:

1. itgs.org.br
2. osm.codes
3. digital-guard.org
4. addressforall.org
5. ... todo o resto.

---

Se sobrar tempo. Ideal estabelecer templates Mustache usando [run_mustache.py](https://github.com/digital-guard/preserv/blob/main/src/run_mustache.py). No código-fonte do WS de cada domínio indicar apenas o template configurado por YAML, não precisamos do NGINX final no git, o que dá mais clareza... Tal como [Less](https://lesscss.org/) faz com CSS. Vale também testar `<<`  e `>>`  no lugar dos separadores default, visto que chaves `{{foo}}` é uma sintaxe válida para o NGINX.

**Comment by cchness** [comment]
Arquivo foi refatorado. Aparentemente apenas em #18 apareceu problema com certificado SSL. Além disso, digital-guard.org, ou seus subdomínios, estão sem certificado.

**Comment by 0e1** [comment]
Vou fechar essa issue por entender que o assunto faz parte de https://github.com/osm-codes/WS/issues/50.
