### ISSUE TITLE
[Ingest] Uruguai - Ingerir BD nacional recebido por Thierry

### ISSUE THREAD

**Issue by ThierryAJean** [AddressForAll/suporte#22]
Encaminhei um email com um link do Onedrive em Operação onde eu coloquei o arquivo recebido do Pablo Brugnoni do INE do Uruguay. Pasta 2024-07-04

**Comment by ThierryAJean** [comment]
CArlos precisa verificar como versionar este dado com o Claiton. É necessário gerar nova versão e não novo pacote.

Carlos precisa aprender com o Claiton como fazer o upload do dado na ESRI.

**Comment by crebollobr** [comment]
Feito
https://github.com/digital-guard/preserv-UY/tree/main/data/_pk0002.02

**Comment by ThierryAJean** [comment]
Carlos, recebi ontem os dados do Uruguai / Uruguay, mas não percebi e não mencionei na nossa reunião. Coloquei no Ondedrive. https://addressforall-my.sharepoint.com/:f:/g/personal/thierry_addressforall_org/EncDIGWHkctDmCdFQfz3c9QBB-i2KHUzO3WUNjTox8kyOQ?e=LuStHo
Vc precisa de quanto tempo para colocar no Openaddresses.io ? Quais são os passos que vc deve seguir?

**Comment by ThierryAJean** [comment]
Carlos preparou tudo, fez um join do idcalle via e Geoaddress. @0e1 vai dar uma olhada para podermos enviar para Openaddresses.io e Overture.
