### ISSUE TITLE
Fazer ingestão dos dados de municipios de camarões

### ISSUE THREAD

**Issue by ThierryAJean** [AddressForAll/suporte#29]
Dados dos municípios de Camaroes foram entregues em Outubro
Atualização recebida em Julho
Gerar makeconf, fazer ingestão e publicar o dado.

**Comment by crebollobr** [comment]
Onde estão os dados?

**Comment by ThierryAJean** [comment]
Vamos colocar os 2 email recebidos de Willy (Camarões) em outubro de 23 e  13 Julho 24 e coloca los no Stable.
As próximas atualizações serão feitas a partir do OSM.

**Comment by ThierryAJean** [comment]
Peter teve reunião com Marcelo e Filipe hoje.
