### ISSUE TITLE
Liberar para atualizar repositório com servidor

### ISSUE THREAD

**Issue by venezianluis** [AddressForAll/suporte#5]
Para sincronizações entre servidor e git:
- Permissão de git pull em `/opt/gits/site`
- Permissão de cp para `/var/www/`

**Comment by ppKrauss** [comment]
As permissoes requerem automacao no [make do projeto WS](https://github.com/AddressForAll/WS/blob/master/src/makefile). @crebollobr precisa criar regras, e ai cada vez que der bug de permissao eu ou voce, como sudors simplesmente rodamos o make adequado.

Provavelmente a regra tera entre os comandos o `chown -R postgres:postgres /opt/gits` e `chmod` com `find` para file (665) e dir (776), e precisamos estudar se o melhor nao seria  `chown postgres:www-data`.  Vai reparar que todos (peter, luis e enio) temos em `groups` os grupos `postgres` e `www-data`.

**Comment by venezianluis** [comment]
**Adendo**
O usuário precisa possuir permissão de `sudo`, alguns incidentes estão onerando a produtividade: 
```
sudo nano api_default.inc.php 
[sudo] password for luis: 
luis is not in the sudoers file.  This incident will be reported.
```

**Comment by crebollobr** [comment]
o usuário luis foi adicionado no grupo sudo.
uid=1007(luis) gid=1007(luis) groups=1007(luis),27(sudo),33(www-data),120(postgres)

Proposta futura, adicionar um grupo "suporte" onde todos os usuários fazem parte, e dono dele seria o usuário daemon 
a permissão seria para dono e grupo

**Comment by ppKrauss** [comment]
Reforcando, no lado /var/www  tambem sera preciso. Por exemplo foi feito pontualmente, para liberar copias:
* `sudo chown postgres:www-data /var/www/addressforall.org/resources/img/*.*`
* `sudo chmod 666 /var/www/addressforall.org/resources/img/*.*`

**Comment by crebollobr** [comment]
Não foi fechado na época.
Se precisar de mais alguma coisa reabrir
