### ISSUE TITLE
servidor com horario incompativel

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/suporte#6]
Como a sede do Instituto AddressForAll esta no Brasil, horario do servidor deveria ser Brasilia.
Atualmente comando `date` do terminal nao esta sincronizado. Por exemplo 6h indicou como "Fri Oct 30 09:12:17 UTC 2020".

**Comment by crebollobr** [comment]
timedatectl
timedatectl list-timezones
timedatectl list-timezones | grep -i sao
timedatectl set-timezone America/Sao_Paulo
