### ISSUE TITLE
HTTPS - Implantar o protocolo

### ISSUE THREAD

**Issue by ThierryAJean** [AddressForAll/suporte#7]
Vamos implantar o protocolo HTTPS até 15/6/21

**Comment by crebollobr** [comment]
Implementado para addressforall.org

Se precisar de outro domínio avisar 

1: addressforall.org
2: addressforall.com
3: api.addressforall.org
4: api-htm.addressforall.org
5: api-test.addressforall.org
6: git.addressforall.org
7: git-raw.addressforall.org
8: osms.addressforall.org
9: preserv.addressforall.org
10: tv.addressforall.org
11: www.addressforall.org
12: c-qr.org
13: demo.c-qr.org
14: hacka.c-qr.org
15: lex.c-qr.org
16: www.c-qr.org
17: brazilplural.com.br
18: caixadeferramentassp.com.br
19: admin.oficial.news
20: api.oficial.news
21: baixar.oficial.news
22: css.oficial.news
23: dl.oficial.news
24: doc.oficial.news
25: ver.oficial.news
26: view.oficial.news
27: itgs.org.br
28: www.itgs.org.br
29: osm.codes
30: olc.osm.codes
31: www.osm.codes
32: qr-c.org
33: osm.qr-c.org
34: www.qr-c.org

**Comment by crebollobr** [comment]
Obs: os links do site vão para http saíndo do htps
